### ISSUE TITLE
스타일 피드백은 여기서 부탁드립니다.

### ISSUE THREAD

**Issue by Moorisong** [Moorisong/MongBit_Frontend#5]
## 개선이 필요하다고 생각되는 부분이 있다면
- 코멘트로 상세히 내용 남겨주시면(캡처 등 이용) 감사하겠습니다.
- 시간 날때마다 적용하도록 할게요!

## 목록
- [x] 노란 버튼들 슬라이드 인 구현
    - 페이지 로드 후 아래->위로
- [x] 아톰 스펙 마무리하기
- [x] 테스트 끝나고 결과 로딩 끝났을때 로그인이 필요하다면
   - '카카오톡 로그인 하고 결과 보기' 텍스트와 로그인 버튼 보여주기
- [x] try chatch 문 처리 어떻게 할건지 확인하고 모두 정리(eslint 참고)
   - 모든 ajax 요청 통일시키기
- [x] 테스트 중 게이지 바 애니메이션 주기

**Comment by WillNeiman** [comment]
![image](https://github.com/Moorisong/MongBit_Frontend/assets/122020165/f19848ae-5691-4652-8ac0-2bfd884ffab0)

마이페이지에서 마이페이지 버튼 안보이게 해주세요

**Comment by Moorisong** [comment]
## 2023 06 14 적용완료
- <img width="670" alt="image" src="https://github.com/Moorisong/MongBit_Frontend/assets/64249489/801351ae-b27d-4854-bf04-aca9a380a04b">
- 마이페이지에서는 마이페이지 이동 아이콘 표시하지 않음

**Comment by Moorisong** [comment]
- [ ] 사이드 바 표시되는 동안 스크롤 방지
- [ ] 사이드바 표시되는 동안 네이 바에도 회색 배경 처리

**Comment by WillNeiman** [comment]
![image](https://github.com/Moorisong/MongBit_Frontend/assets/122020165/fa42f9ee-7499-4779-abd3-68b1017cfbb7)

- 비회원 댓글 작성 가능한 문제
- 로그인 페이지로 이동시켜주세요

**Comment by Moorisong** [comment]
개선 완료 했습니다.

**Comment by WillNeiman** [comment]
광고 배너

### iframe
<iframe src="https://ads-partners.coupang.com/widgets.html?id=665416&template=carousel&trackingCode=AF7346840&subId=&width=400&height=90&tsource=" width="400" height="90" frameborder="0" scrolling="no" referrerpolicy="unsafe-url"></iframe>


### js
<script src="https://ads-partners.coupang.com/g.js"></script>
<script>
   new PartnersCoupang.G({"id":665416,"template":"carousel","trackingCode":"AF7346840","width":"400","height":"90","tsource":""});
</script>

**Comment by WillNeiman** [comment]
![image](https://github.com/Moorisong/MongBit_Frontend/assets/122020165/b8943c60-efde-48e2-ba74-c9b0105d6809)
![image](https://github.com/Moorisong/MongBit_Frontend/assets/122020165/db5c339a-8231-406d-aafa-63e02e7eba1e)
![image](https://github.com/Moorisong/MongBit_Frontend/assets/122020165/a2c1ead0-76d8-4853-8884-3dd895e3f3ac)
위와 같이 상호작용한 버튼은 마우스 호버링 시에 진한 색깔로 트랜지션 0.3초 주기

**Comment by WillNeiman** [comment]
![image](https://github.com/Moorisong/MongBit_Frontend/assets/122020165/3d3f56f2-1b6a-4f0f-b75c-0cc3029d681d)
이미지 뿐만 아니라 텍스트영역도 포함해서, 해당 컨테이너 전체를 클릭 가능한 영역으로 설정하기

**Comment by WillNeiman** [comment]
![image](https://github.com/Moorisong/MongBit_Frontend/assets/122020165/8ee88e3f-2bdf-4997-a28d-d550d4626169)
마이페이지에서 결과페이지로 넘어갈 때 상단에 과도한 공백, 이미지가 가로로 찌부가 되는 문제 수정 요망

**Comment by jj123859** [comment]
![image](https://github.com/WillNeiman/MongBit_Backend/assets/102505489/9679cde1-cf2c-47f9-a4df-5b2d88ecb517)
이 화면에서(테스트 상세페이지) 체크된 사진위에 마우스 올리면 클릭할 수 있는것 처럼 마우스 바뀝니다. 그런데 아무 기능은 없어서 바꿔야할 것 같아요.

**Comment by WillNeiman** [comment]
![image](https://github.com/Moorisong/MongBit_Frontend/assets/122020165/bb0dec89-1c1b-498c-818e-897e2bfa0758)
여기 정렬 기준이 링크 복사됨 텍스트 기준으로 되어있는데 다시해보기 버튼 기준으로 쎈터 잡아주세요

**Comment by jj123859** [comment]
![image](https://github.com/Moorisong/MongBit_Frontend/assets/102505489/7044791a-8451-448e-afa7-448a9caba112)
링크 복사 부분이 이렇게 바뀌는데 나오는 문자가(링크복사됨, 링크복사) 서로 바뀌어야 할 것 같습니다

**Comment by jj123859** [comment]
![image](https://github.com/Moorisong/MongBit_Frontend/assets/102505489/922c089c-607f-4b3b-89be-be40f3e7e6be)
마이페이지 부분 테스트 결과에 사진이 너무 큰것 같습니다. 파란 라인 정도로 맞추는 건 어떨까요?

**Comment by WillNeiman** [comment]
[건재림] [오전 9:47] 피드백 1. 테스트 진행 페이지의 height가 question의 길이에 따라 가변적으로 변하는 문제 해결. 최소 크기를 좀 더 크게 잡아주거나 question 컴포넌트의 공간을 더 넉넉하게 허용할것
![image](https://github.com/Moorisong/MongBit_Frontend/assets/122020165/8319d979-877e-47ea-b24f-c3f5f992f176)
[건재림] [오전 9:48] 피드백 2. 프로그레스바가 답변을 누르기도 전에 차올라있음. 질문 1일때는 아예 비어있다가 클릭하면 차오르는 식으로 진행하는 게 좋은 ux

**Comment by WillNeiman** [comment]
![image](https://github.com/Moorisong/MongBit_Frontend/assets/122020165/d9f000af-509a-40e9-bcf6-213decdf0b71)
![image](https://github.com/Moorisong/MongBit_Frontend/assets/122020165/9e2c0906-7b79-4dec-a5c0-6eb577a3b77b)
첫번째 질문 클릭 전에 비어있음 > 올바름
12번 질문 클릭 전에 꽉차있음 > 빨간 박스까지만 오는 게 올바름

[건재림] [오후 10:42] 마지막에 12번 누르면 끝까지 차오르는 애니메이션 끝나고 나서 화면 넘어가도록
[건재림] [오후 10:42] 안그러면 영원히 꽉차는 프로그레스바를 못봅니다

**Comment by WillNeiman** [comment]
![image](https://github.com/Moorisong/MongBit_Frontend/assets/122020165/5502fb9e-c31e-452d-8b93-c43f12e1205d)

- [ ] 쿠팡보기 버튼 내 cursor: pointer; 전체 적용하기. 현재 드래그 가능
